#服务端口不过多解释
server:
  port: 8081


#选择数据库连接池时，考虑一下还是使用hikariCP，因为其相对简单速度也最快
#虽然功能全面和扩展略逊于阿里的druid
spring:
  datasource:
    username: root
    password: SZjMAA7a
    url: jdbc:mysql://10.199.1.139:3306/ysl_test?useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      read-only: false
      maximum-pool-size: 20
  resources:
    static-locations: classpath:/
  mvc:
    view:
      suffix: .html